language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

env:
  - LIBYAML="true"
  - LIBYAML="false"

install:
  - pip install -q testtools fixtures
  - if [[ $LIBYAML == 'true' ]]; then sudo apt-get -qq install libyaml-dev; fi
  - python setup.py -q install

script:
  - python setup.py -q test
